### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by peteketcham**
redid logging and print statements
getopt -> argparse
wrapped main into a main()
linted w/ Black
added logging level option (-verbose, -v, -vv, -vvv...)
added quiet option (-q, -quiet)

### CODE REVIEW

**Review by samule-i — COMMENTED** [review]
I appreciate the fresh formatting, the file is a lot more readable, and argparse seems easier to read than getopt... however I'm getting a few issues whilst testing this branch.

-le behaves like -l
--list-errors, --verbose, -v, --quiet, -q are not recognized options
--listpaths requires an argument

The main problem I'm seeing here though is a poor handling of files when a keyboardInterrupt comes into the script during ffmpeg running, The file doesn't seem to get restored consistently and then, in my testing the file is locked and any attempt by the script to repair it is met with "PermissionError: [WinError 5] Access is denied: filepath"

Also, is it the linter that changed single quotes to double quotes? I can't find anything in a light search that seems to state that double quotes are more correct or that single quotes are causing an issue other than as a stylistic choice, genuinely interest on learning what the reasons behind this are.

argparse and the formatting seem good though, along with wrapping main, I appreciate it.

**Comment by peteketcham** [comment]
Good catches!
I renamed --listpaths to --list; added that back
--le and --list-errors are fixed (mostly.  it'll write the errors to log
*again* when called.)
--quiet, -q, -v, --verbose, (and -vv) work for me when running "python
main.py [-vv|-v|-q|--quiet|--verbose] --list-errors" and for "python
main.py -vv -s"  what is the command you're running that doesn't change the
behavior?

I'm also not getting the KeyboardInterrupt behavior you're seeing, but then
I'm running on Windows 7.  Are you on 10?  I'll have to try there next.

For single vs double quotes, the linter (Black) did it automatically.  The
one case I could see here is that when using one vs the other is the need
to use the opposite of what could be in the string-- double is not valid
for windows filenames, so it could never be in the file name.  you could
potentially run into issues when doing 'jon's movie.avi' vs "jon's
movie.avi".  You couldn't have a "Dwayne "The Rock" Johnson.avi".  Not sure
if that's a concern here though, I wasn't thinking about input sanitization
here.

The updates are on my fork; I'll do a last once over and then another pull
request in a few hours.

**Comment by samule-i** [comment]
It seems like the issue with permission errors on keyboard interrupt can occur if you cancel ffmpeg too soon after starting, within ~1s of ffmpeg starting.

Quite possibly has nothing to do with your PR and more likely something to do with ffmpeg itself and is probably present in all previous versions... I'll look into it a bit myself but I wouldn't worry too much.

in regards to single v double quotes, you raise some good points and I'll look at it more, but seriously consider switching over personally.

Another issue that's seemed to be happening is that the behaviour of --focus-directory no longer seems to add the new directory to the library or encode any of the files within it.

**Comment by samule-i** [comment]
It's been a while since I've heard back, and some of these features didn't work for me.

Most of the proposed features have now been put into the master using this pr as a reference so I'm closing this pr. Thankyou for the help.

**Pull request closed without merging**
